server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
